
# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Versión de Markdown
markdown: kramdown

# Email
email: includepoetry@gmail.com

# Descripcón del sitio
description: Aprende a programar C/C++ y Karel.

# Google services
google_analytics: UA-74086952-1

# Base del sitio
url: "https://include-poetry.github.io"
host: 0.0.0.0

# Excuidos de la conversión
exclude: [No en git]

incremental: true;

paginate: 8
paginate_path: "/Poetry/Pagina-:num/"

gems: [jekyll-paginate]

collections:
  C: 
    output: true
    permalink: /C++/:path/
  Karel:
    output: true
    permalink: /Karel/:path/
  posts:
    output: true
    permalink: /Poetry/:year/:month/:day/:title/