# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Descripcón del sitio
description: Aprende a programar C/C++ y Karel de la manera más fácil y con enfoque en la OMI.

# Autor
author: rivel_co

# Versión de Markdown
markdown: kramdown

# Email
email: includepoetry@gmail.com

# Google services
google_analytics: UA-74086952-1

# Base del sitio url: "http://localhost:4000"  url: "http://169.254.223.56:4000"
url: "http://192.168.1.65:4000"
host: 0.0.0.0

# Excuidos de la conversión
exclude: [No en git, Montar.bat, Sublime  iP.sublime-project, Sublime  iP.sublime-workspace]

incremental: true;

paginate: 8
paginate_path: "/Poetry/Pagina-:num/"

#gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
gems: [jekyll-paginate]

collections:
  C: 
    output: true
    permalink: /C++/:path/
  Karel:
    output: true
    permalink: /Karel/:path/
  Topicos-C:
    output: true
    permalink: /Topicos-adicionales/C++/:categories/:title/
  Topicos-Karel:
    output: true
    permalink: /Topicos-adicionales/Karel/:categories/:title/
  Apuntes-Bio:
    output: true
    permalink: /Biology/:categories/:year/:month/:day/:title/
  Apuntes-Qui:
    output: true
    permalink: /Chemistry/:categories/:year/:month/:day/:title/
  Apuntes-Fis:
    output: true
    permalink: /Physics/:categories/:year/:month/:day/:title/
  Apuntes-Mat:
    output: true
    permalink: /Math/:categories/:year/:month/:day/:title/
  posts:
    output: true
    permalink: /Poetry/:categories/:year/:month/:day/:title/