# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Descripcón del sitio
description: Iniciativa dedicada a la divulgación de la ciencia y al entrenamiento de competidores de olimpiadas de ciencias en México, como la OMI, ONB, OMF y OMM.

# Email
email: contacto@include-poetry.com

# Facebook
facebook:
  app_id: 201218926955149

# Autor
author: rivel_co

# Versión de Markdown
markdown: kramdown

# Google services
google_analytics: UA-74086952-1

# Base del sitio
url: "https://www.include-poetry.com"

# Excuidos de la conversión
exclude:
  - vendor

# Gemas
plugins: 
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "/Blog/Pagina-:num/"

# Variables del sitio
logo-grande-n: "/Multimedia/Logo/IPoetryN.png"
logo-chico-n: "/Multimedia/Logo/IPN.png"
logo-grande-b: "/Multimedia/Logo/IPoetryB.png"
logo-chico-b: "/Multimedia/Logo/IPB.png"
logo-pluma: "/Multimedia/Logo/RPlumaN.png"
iP-Sources: "https://www.include-poetry.com/IP-Sources"

# Colecciones 
collections:
  Equipo:
    output: true
    permalink: /Equipo/:categories/:title/
  Poetry:
    output: false
    permalink: /Poetry/:year/:month/:day/:title/
  posts:
    output: true
    permalink: /Blog/:categories/:year/:month/:day/:title/