# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Descripcón del sitio
description: Aprende a programar C/C++ y Karel de la manera más fácil y con enfoque en la OMI.

# Autor
author: rivel_co

# Versión de Markdown
markdown: kramdown

# Email
email: includepoetry@gmail.com

# Google services
google_analytics: UA-74086952-1

# Base del sitio
url: "https://include-poetry.github.io"
host: 0.0.0.0

# Excuidos de la conversión
exclude: [No en git]

incremental: true;

paginate: 8
paginate_path: "/Poetry/Pagina-:num/"

gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

collections:
  C: 
    output: true
    permalink: /C++/:path/
  Karel:
    output: true
    permalink: /Karel/:path/
  Topicos-C:
    output: true
    permalink: /Topicos-adicionales/C++/:categories/:title/
  Topicos-Karel:
    output: true
    permalink: /Topicos-adicionales/Karel/:categories/:title/
  Apuntes-Bio:
    output: true
    permalink: /biology/:year/:month/:day/:title/
  Apuntes-Qui:
    output: true
    permalink: /chemistry/:year/:month/:day/:title/
  posts:
    output: true
    permalink: /Poetry/:year/:month/:day/:title/